server {
    listen       8080;
    server_name  localhost;
    root   /usr/share/nginx/html;
    index  index.html;

    # Serve /privacy and /tos without the .html suffix.
    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    error_page 500 502 503 504 /50x.html;
}
